//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.logs = new HashSet<log>();
        }
    
        public int id { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string sdt { get; set; }
        public Nullable<int> id_xa { get; set; }
        public string user_name { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> id_quy_mo { get; set; }
        public Nullable<int> id_huyen { get; set; }
        public Nullable<int> id_co_so { get; set; }
        public Nullable<int> id_role { get; set; }
    
        public virtual Co_so Co_so { get; set; }
        public virtual Huyen Huyen { get; set; }
        public virtual quy_mo quy_mo { get; set; }
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<log> logs { get; set; }
        public virtual Xa Xa { get; set; }
    }
}
